Repository kubernetes/steering, pull requests merged in 2018-07, with the labels that each got.

#55 SECURITY_CONTACTS: initial commit
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#26 Change Kubernetes status in CNCF
  cncf-and-k8s.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#56 README: @philips move from CoreOS to Red Hat
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#59 thockin steps down from steering
  OWNERS_ALIASES
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
