Repository kubernetes/steering, pull requests merged in 2018-08, with the labels that each got.

#67 README: document SC accounts
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 Remove backlog.md in favor of project board
  README.md
  backlog.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Update the elections charter for 2018
  elections.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#70 Add link to 2018 voter's guide
  elections.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
