Repository kubernetes/steering, pull requests merged in 2019-08, with the labels that each got.

#119 Update for 2019 election
  elections.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#122 Update election doc with 2019 information.
  elections.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 update meeting cadence
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Fixed Minor typo
  charter.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
