Repository kubernetes/steering, pull requests merged in 2020-10, with the labels that each got.

#181 Update members with results of 2020 election
  OWNERS_ALIASES
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#182 Add public CNCF maintainers list to onboarding checklist
  onboarding.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 Update liasons with new steering members
  liaisons.md
  onboarding.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 Add twitter account handover to onboarding checklist
  onboarding.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 Add term limits to the Kubernetes Steering Committee
  elections.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash
